name: Build and Deploy backend to Azure Container App

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-acr:
    name: Build and Push Docker Image to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Image to ACR
        uses: azure/cli@v1
        with:
          inlineScript: |
            az acr build --registry lucianaacr01 --image luciana-backend:latest ./backend

  deploy-containerapp:
    name: Deploy to Azure Container App
    runs-on: ubuntu-latest
    needs: build-and-push-acr

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: luciana-backend
          resourceGroup: luciana_resource_group
          imageToDeploy: lucianaacr01.azurecr.io/luciana-backend:latest
          registryUrl: lucianaacr01.azurecr.io
          acrName: lucianaacr01
          targetPort: 8000
